# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Environment variables (ENV['...']) are set in the file config/application.yml.
# See http://railsapps.github.com/rails-environment-variables.html
puts 'ROLES'
YAML.load(ENV['ROLES']).each do |role|
  Role.find_or_create_by_name({ :name => role }, :without_protection => true)
  puts 'role: ' << role
end
puts 'DEFAULT USERS'
user = User.find_or_create_by_email :name => ENV['ADMIN_NAME'].dup, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
puts 'user: ' << user.name
user.add_role :admin

Year.delete_all
Year.create(name: 2000)
Year.create(name: 2001)
Year.create(name: 2002)
Year.create(name: 2003)
Year.create(name: 2004)
Year.create(name: 2005)
Year.create(name: 2006)
Year.create(name: 2007)
Year.create(name: 2008)
Year.create(name: 2009)
Year.create(name: 2010)
Year.create(name: 2011)
Year.create(name: 2012)
Year.create(name: 2013)
puts 'Created Years'

AwardType.delete_all
AwardType.create(name: 'Chief Scout\'s Bronze Award')
AwardType.create(name: 'Chief Scout\'s Silver Award')
AwardType.create(name: 'Chief Scout\'s Gold Award')
AwardType.create(name: 'Chief Scout\'s Diamond Award')
AwardType.create(name: 'Chief Scout\'s Platinum Award')
AwardType.create(name: 'Queen\'s Scout Award')
puts 'Created Award Types'

MembershipType.create!(name: 'Beavers')
MembershipType.create!(name: 'Cubs')
MembershipType.create!(name: 'Scouts')
MembershipType.create!(name: 'Explorers')
MembershipType.create!(name: 'Network')
MembershipType.create!(name: 'Active Support')
MembershipType.create!(name: 'Leaders')
MembershipType.create!(name: 'Executive Committee')
puts 'Created Membership Types'

OrganisationType.delete_all
county = OrganisationType.create(name: 'Scout County')
district = OrganisationType.create(name: 'Scout District')
group = OrganisationType.create(name: 'Scout Group')
explorers = OrganisationType.create(name: 'Explorer Scout Unit')
network = OrganisationType.create(name: 'Network Unit')
asu = OrganisationType.create(name: 'Active Support Unit')
puts 'Created Organisation Types'

Organisation.delete_all
cheshire = Organisation.create(name: 'Cheshire Scouts', organisation_type: county)
alderley = Organisation.create(name: 'Alderley', organisation_type: district, parent: cheshire)
chester = Organisation.create(name: 'Chester', organisation_type: district, parent: cheshire)
ellesmere = Organisation.create(name: 'Ellesmere Port and Neston', organisation_type: district, parent: cheshire)
knutsford = Organisation.create(name: 'Knutsford', organisation_type: district, parent: cheshire)
macc = Organisation.create(name: 'Macclesfield and Congleton', organisation_type: district, parent: cheshire)
mersey = Organisation.create(name: 'Mersey Weaver', organisation_type: district, parent: cheshire)
mid = Organisation.create(name: 'Mid Cheshire', organisation_type: district, parent: cheshire)
sw = Organisation.create(name: 'South West Cheshire', organisation_type: district, parent: cheshire)
warringtonE = Organisation.create(name: 'Warrington East', organisation_type: district, parent: cheshire)
warringtonW = Organisation.create(name: 'Warrington West', organisation_type: district, parent: cheshire)
puts 'Created Districts'



Organisation.create!(name: '1st Chelford', organisation_type: group, parent: alderley)
Organisation.create!(name: '1st Goostrey', organisation_type: group, parent: alderley)
Organisation.create!(name: '1st Handforth', organisation_type: group, parent: alderley)
Organisation.create!(name: '1st Holmes Chapel', organisation_type: group, parent: alderley)
Organisation.create!(name: '1st Lindow (St John\'s)', organisation_type: group, parent: alderley)
Organisation.create!(name: '1st Wilmslow', organisation_type: group, parent: alderley)
Organisation.create!(name: '4th Wilmslow (U.R.C.)', organisation_type: group, parent: alderley)
Organisation.create!(name: '5th Wilmslow', organisation_type: group, parent: alderley)
Organisation.create!(name: '6th Wilmslow', organisation_type: group, parent: alderley)
Organisation.create!(name: 'Alderley Edge', organisation_type: group, parent: alderley)
Organisation.create!(name: 'Lindow Explorer Scout Unit', organisation_type: explorers, parent: alderley)
Organisation.create!(name: 'Terra Nova School', organisation_type: group, parent: alderley)
Organisation.create!(name: 'The Edge Explorer Scout Unit', organisation_type: explorers, parent: alderley)
Organisation.create!(name: 'Vikings Explorer Scout Unit', organisation_type: explorers, parent: alderley)
Organisation.create!(name: 'YL Explorer Scout Unit', organisation_type: explorers, parent: alderley)
Organisation.create!(name: '18th Chester (St. Mary\'s)', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Ashton and Manley', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Christleton', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Farndon', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Guilden Sutton', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Malpas', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Saltney (St Mark\'s )', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Sandstone', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Saughall', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Tarporley', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Tarvin', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Tilston', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Upton-By-Chester', organisation_type: group, parent: chester)
Organisation.create!(name: '1st Waverton', organisation_type: group, parent: chester)
Organisation.create!(name: '40th Chester', organisation_type: group, parent: chester)
Organisation.create!(name: '42nd Chester', organisation_type: group, parent: chester)
Organisation.create!(name: '48th Chester (St Columba\'s)', organisation_type: group, parent: chester)
Organisation.create!(name: '5th Blacon (Holy Trinity)', organisation_type: group, parent: chester)
Organisation.create!(name: '8th Chester', organisation_type: group, parent: chester)
Organisation.create!(name: 'Cestrian', organisation_type: group, parent: chester)
Organisation.create!(name: 'Dewa Explorer Scout Unit', organisation_type: explorers, parent: chester)
Organisation.create!(name: 'Farndon Explorer Scout Unit', organisation_type: explorers, parent: chester)
Organisation.create!(name: 'Maverik Explorer Scout Unit', organisation_type: explorers, parent: chester)
Organisation.create!(name: 'Renegades Explorer Scout Unit', organisation_type: explorers, parent: chester)
Organisation.create!(name: 'Wolf Explorer Scout Unit', organisation_type: explorers, parent: chester)
Organisation.create!(name: '1st Burton in Wirral', organisation_type: group, parent: ellesmere)
Organisation.create!(name: '1st Great Sutton', organisation_type: group, parent: ellesmere)
Organisation.create!(name: '1st Sutton (Wirral)', organisation_type: group, parent: ellesmere)
Organisation.create!(name: '1st Willaston', organisation_type: group, parent: ellesmere)
Organisation.create!(name: '39th Ellesmere Port', organisation_type: group, parent: ellesmere)
Organisation.create!(name: '4th Ellesmere Port', organisation_type: group, parent: ellesmere)
Organisation.create!(name: '6th Ellesmere Port', organisation_type: group, parent: ellesmere)
Organisation.create!(name: '8th Ellesmere Port St Thomas\' Whitby', organisation_type: group, parent: ellesmere)
Organisation.create!(name: 'Allegro Explorer Scout Unit', organisation_type: explorers, parent: ellesmere)
Organisation.create!(name: 'Ardvark Explorer Scout Unit', organisation_type: explorers, parent: ellesmere)
Organisation.create!(name: 'Dee Sea Scouts', organisation_type: group, parent: ellesmere)
Organisation.create!(name: 'Discovery Explorer Scout Unit', organisation_type: explorers, parent: ellesmere)
Organisation.create!(name: 'Endeavour Explorer Scout Unit', organisation_type: explorers, parent: ellesmere)
Organisation.create!(name: 'Hinderton', organisation_type: group, parent: ellesmere)
Organisation.create!(name: 'Phoenix Explorer Scout Unit', organisation_type: explorers, parent: ellesmere)
Organisation.create!(name: '1st Knutsford', organisation_type: group, parent: knutsford)
Organisation.create!(name: '1st Mobberley', organisation_type: group, parent: knutsford)
Organisation.create!(name: '2nd Knutsford (Crosstown)', organisation_type: group, parent: knutsford)
Organisation.create!(name: '5th Knutsford', organisation_type: group, parent: knutsford)
Organisation.create!(name: 'Knutsford Kite Explorer Scout Unit', organisation_type: explorers, parent: knutsford)
Organisation.create!(name: '15th Macclesfield (U.R.C.) Sea Scout Group', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Buglawton (St. John\'s)', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Congleton', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Gawsworth (St. James\')', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Hurdsfield (Parish Church)', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Mossley', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Poynton (St Georges)', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Prestbury', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Rainow', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Sutton (St James)', organisation_type: group, parent: macc)
Organisation.create!(name: '1st Tytherington', organisation_type: group, parent: macc)
Organisation.create!(name: '24th Macclesfield (Beech Lane Methodist)', organisation_type: group, parent: macc)
Organisation.create!(name: '2nd Bollington', organisation_type: group, parent: macc)
Organisation.create!(name: '2nd Poynton', organisation_type: group, parent: macc)
Organisation.create!(name: '3rd Macclesfield Upton Priory', organisation_type: group, parent: macc)
Organisation.create!(name: '3rd Poynton (Bulkeley)', organisation_type: group, parent: macc)
Organisation.create!(name: '6th Congleton (Westheath)', organisation_type: group, parent: macc)
Organisation.create!(name: '6th Macclesfield (Parish Church)', organisation_type: group, parent: macc)
Organisation.create!(name: '8th Macclesfield (St.Paul\'s)', organisation_type: group, parent: macc)
Organisation.create!(name: 'Dane Valley', organisation_type: group, parent: macc)
Organisation.create!(name: 'Maori Explorer Scout Unit', organisation_type: explorers, parent: macc)
Organisation.create!(name: 'Samurai Explorer Scout Unit', organisation_type: explorers, parent: macc)
Organisation.create!(name: 'Spartan Explorer Scout Unit', organisation_type: explorers, parent: macc)
Organisation.create!(name: 'Titan Explorer Scout Unit', organisation_type: explorers, parent: macc)
Organisation.create!(name: 'Trojan Explorer Scout Unit', organisation_type: explorers, parent: macc)
Organisation.create!(name: 'Viking Explorer Scout Unit', organisation_type: explorers, parent: macc)
Organisation.create!(name: 'Zulu Explorer Scout Unit', organisation_type: explorers, parent: macc)
Organisation.create!(name: '10th Widnes (Hough Green C of E)', organisation_type: group, parent: mersey)
Organisation.create!(name: '12th Widnes', organisation_type: group, parent: mersey)
Organisation.create!(name: '14th Widnes (Farnworth Methodist)', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Halton', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Helsby B.I.', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Ince and Elton', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Moore', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Newton and Kingsley', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Norley', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Weston & Weston Point', organisation_type: group, parent: mersey)
Organisation.create!(name: '1st Whitley', organisation_type: group, parent: mersey)
Organisation.create!(name: '2nd Halton (St Augustine\'s)', organisation_type: group, parent: mersey)
Organisation.create!(name: '3rd Frodsham Sea Scouts', organisation_type: group, parent: mersey)
Organisation.create!(name: '3rd/9th Runcorn', organisation_type: group, parent: mersey)
Organisation.create!(name: '4th Frodsham (Overton)', organisation_type: group, parent: mersey)
Organisation.create!(name: '4th Runcorn', organisation_type: group, parent: mersey)
Organisation.create!(name: '4th Widnes (St Bede\'s)', organisation_type: group, parent: mersey)
Organisation.create!(name: '6th Runcorn (St. Edward\'s)', organisation_type: group, parent: mersey)
Organisation.create!(name: '8th Widnes (St. Thomas\')', organisation_type: group, parent: mersey)
Organisation.create!(name: 'Aquila Explorer Scout Unit', organisation_type: explorers, parent: mersey)
Organisation.create!(name: 'Beacon Explorer Scout Unit', organisation_type: explorers, parent: mersey)
Organisation.create!(name: 'Cestrian Explorer Scout Unit', organisation_type: explorers, parent: mersey)
Organisation.create!(name: 'YL Explorer Scout Unit', organisation_type: explorers, parent: mersey)
Organisation.create!(name: 'Xcape Explorer Scout Unit', organisation_type: explorers, parent: mersey)
Organisation.create!(name: '1st Antrobus & Comberbach Sea Scout Group', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Barnton', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Cuddington & Sandiway', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Davenham (Parish Church)', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Hartford (Northwich)', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Lostock Gralam', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Moulton', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Over St John\'s (Winsford)', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Weaverham Sea Scouts', organisation_type: group, parent: mid)
Organisation.create!(name: '1st Winnington', organisation_type: group, parent: mid)
Organisation.create!(name: '2nd Middlewich', organisation_type: group, parent: mid)
Organisation.create!(name: '2nd Wharton', organisation_type: group, parent: mid)
Organisation.create!(name: 'Endurance Explorer Scout Unit', organisation_type: explorers, parent: mid)
Organisation.create!(name: 'Forlorn Hope Explorer Scout Unit', organisation_type: explorers, parent: mid)
Organisation.create!(name: 'Hartford Explorer Scout Unit', organisation_type: explorers, parent: mid)
Organisation.create!(name: 'St Wilfrids', organisation_type: group, parent: mid)
Organisation.create!(name: '10th South West Cheshire (Haslington)', organisation_type: group, parent: sw)
Organisation.create!(name: '12th South West Cheshire (Shavington)', organisation_type: group, parent: sw)
Organisation.create!(name: '15th South West Cheshire (Baptist Church)', organisation_type: group, parent: sw)
Organisation.create!(name: '16th South West Cheshire ( Crewe Green)', organisation_type: group, parent: sw)
Organisation.create!(name: '17th South West Cheshire (7th Crewe)', organisation_type: group, parent: sw)
Organisation.create!(name: '18th South West Cheshire', organisation_type: group, parent: sw)
Organisation.create!(name: '1st South West Cheshire St Andrews', organisation_type: group, parent: sw)
Organisation.create!(name: '22nd South West Cheshire (1st Audlem)', organisation_type: group, parent: sw)
Organisation.create!(name: '23rd South West Cheshire (2nd Wheelock)', organisation_type: group, parent: sw)
Organisation.create!(name: '25th South West Cheshire (Bunbury & District)', organisation_type: group, parent: sw)
Organisation.create!(name: '26th South West Cheshire (1st Willaston)', organisation_type: group, parent: sw)
Organisation.create!(name: '28th South West Cheshire (Wybunbury)', organisation_type: group, parent: sw)
Organisation.create!(name: '30th South West Cheshire (Hightown Methodist Crewe)', organisation_type: group, parent: sw)
Organisation.create!(name: '35th South West Cheshire (Wistaston)', organisation_type: group, parent: sw)
Organisation.create!(name: '38th South West Cheshire 3rd Nantwich Church', organisation_type: group, parent: sw)
Organisation.create!(name: '39th South West Cheshire (3rd Sandbach)', organisation_type: group, parent: sw)
Organisation.create!(name: '3rd South West Cheshire (Wolverton)', organisation_type: group, parent: sw)
Organisation.create!(name: '40th South West Cheshire (2nd Brereton)', organisation_type: group, parent: sw)
Organisation.create!(name: '41st South West Cheshire (Stapeley) Scout Group', organisation_type: group, parent: sw)
Organisation.create!(name: '5th South West Cheshire (1st Elworth)', organisation_type: group, parent: sw)
Organisation.create!(name: '9th South West Cheshire (Wrenbury)', organisation_type: group, parent: sw)
Organisation.create!(name: 'Bunbury Explorer Scout Unit', organisation_type: explorers, parent: sw)
Organisation.create!(name: 'Drake Explorer Scout Unit', organisation_type: explorers, parent: sw)
Organisation.create!(name: 'Fiennes Explorer Scout Unit', organisation_type: explorers, parent: sw)
Organisation.create!(name: 'Shipton Explorer Scout Unit', organisation_type: explorers, parent: sw)
Organisation.create!(name: 'Wilson Explorer Scout Unit', organisation_type: explorers, parent: sw)
Organisation.create!(name: 'Wilson House South West Cheshire', organisation_type: group, parent: sw)
Organisation.create!(name: '12th Warrington East (1st Birchwood)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '13th Warrington East (St Elphins Own)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '17th Warrington East (3rd Lymm)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '18th Warrington East (4th Lymm)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '19th Warrington East (Culcheth Methodist)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '20th Warrington East (Glazebury)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '22nd Warrington East (1st Hollins Green)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '25th Warrington East St. Wilfrid\'s Grappenhall', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '26th Warrington East (2nd Padgate)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '27th Warrington East (Woolston)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '3rd Warrington East (1st Culcheth)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '5th Warrington East (1st Oughtrington)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '6th Warrington East (1st Thelwall)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '8th Warrington East (Croft)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: '9th Warrington East (Gorse Covert)', organisation_type: group, parent: warringtonE)
Organisation.create!(name: 'Antartic Explorer Scout Unit', organisation_type: explorers, parent: warringtonE)
Organisation.create!(name: 'Harrier Explorer Scout Unit', organisation_type: explorers, parent: warringtonE)
Organisation.create!(name: 'Hawk Explorer Scout Unit', organisation_type: explorers, parent: warringtonE)
Organisation.create!(name: '10th Warrington (Sankey St Marys)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '15th Warrington (St Josephs)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '16th Warrington (1st Burtonwood)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '1st/14th Warrington', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '21st Warrington (1st Appleton)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '28th Warrington (Penketh)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '2nd Warrington (St James)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '30th Warrington (Penketh Methodist)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '31st Warrington Workingmens Mission', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '32nd Warrington West', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '33rd Warrington West', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '4th Warrington (1st Stockton Heath)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: '7th Warrington (Sankey Valley)', organisation_type: group, parent: warringtonW)
Organisation.create!(name: 'Amazon Explorer Scout Unit', organisation_type: explorers, parent: warringtonW)
Organisation.create!(name: 'Mayan Explorer Scout Unit', organisation_type: explorers, parent: warringtonW)
Organisation.create!(name: 'Phoenix Explorer Scout Unit', organisation_type: explorers, parent: warringtonW)
Organisation.create!(name: 'Tsunami Explorer Scout Unit', organisation_type: explorers, parent: warringtonW)
Organisation.create!(name: 'Viking Explorer Scout Unit', organisation_type: explorers, parent: warringtonW)

puts 'Created Groups'
puts 'Created Organisations'